spring.application.name=library-management

spring.datasource.url=jdbc:postgresql://localhost:5433/library_db
spring.datasource.username=library_admin
spring.datasource.password=library_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

library.max-active-loans=5
library.max-unpaid-fine=100000
library.max-renew-count=2
library.loan-period-days=14
library.fine-per-day=5000
library.max-fine=20000