spring.application.name=library-management

server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/library_db
spring.datasource.username=library_admin
spring.datasource.password=library_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=86400000

library.max-active-loans=5
library.max-unpaid-fine=100000
library.max-renew-count=2
library.loan-period-days=14
library.fine-per-day=5000
library.max-fine=20000