spring.application.name=library-management

server.port=8080

logging.level.LIBRARY_EVENTS=INFO

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:55432/library_db}
spring.datasource.username=library_admin
spring.datasource.password=library_pass
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

security.basic.username=${LIBRARY_BASIC_USERNAME:admin}
security.basic.password=${LIBRARY_BASIC_PASSWORD:test123}

library.max-active-loans=5
library.max-unpaid-fine=100000
library.max-renew-count=2
library.loan-period-days=14
library.fine-per-day=5000
library.max-fine=20000
library.max-overdue-days=7